application:
  image: 'debian'
  volumes:
    - ./:/var/www/app
  tty: true
front:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
  volumes_from:
    - application
  links:
    - node_first
    - node_second
node_first:
  image: 'node:latest'
  volumes_from:
    - application
  command: node /var/www/app/server_first.js
  links:
    - rabbit
node_second:
  image: 'node:latest'
  volumes_from:
    - application
  command: node /var/www/app/server_second.js
  links:
    - rabbit
rabbit:
  image: 'rabbitmq:latest'
  environment:
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=user
